@PaymentSimulator.Api_HostAddress = http://localhost:5075

Post {{PaymentSimulator.Api_HostAddress}}/api/payment/process
Content-Type: application/json
{
  "paymentId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "amount": 199.99,
  "currency": "PHP",
  "paymentMethod": {
    "type": "CreditCard",
    "cardLast4": "4242",
    "cardBrand": "Visa"
  },
  "customer": {
    "customerId": "CUST-12345",
    "email": "jane.doe@example.com"
  },
  "reference": "ORDER-67890"
}
###
